---
title: "Reproducible Report for Species in Maritimes Region - for Internal DFO use only"
author: Synthesis prepared by the MSP Team
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  html_document:
    theme: paper
    toc: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

```{r Define Site, echo=FALSE, include=FALSE, cache=FALSE}

rm(list=ls(all=TRUE))
AquaSiteName <- "FarmersLedge"
PEZversion <- "4748m"
minYear <- 2002
cat(AquaSiteName)
```
```{r setup, echo=FALSE, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, fig.align="left")
library(knitr)
library(rgdal)
library(maps)
library(lubridate)

```
```{r source functions, echo=FALSE, include=FALSE, cache=FALSE}
source("site_map.r")
source("plot_wsdb.r")
source("filter_wsdb.r")
```

```{r Set up paths, echo=FALSE, include=FALSE, cache=FALSE}
dataPath <- file.path("../outputs",paste0(AquaSiteName,PEZversion))
polyPath <- "../../../Data/Zones/SearchPEZpolygons"
site <- readOGR(polyPath,layer=paste0("Site_",AquaSiteName))
wsdbFile <- file.path("../../../Data/NaturalResources/Species/Cetaceans/WSDB","MarWSDBSightingsForCGomez_27Oct2020.csv")
```
```{r read baseline data for maps, echo=FALSE, include=FALSE, cache=FALSE}
landGDB <- "../../../Data/Boundaries/Coast50K/Coastline50k.gdb"
land <- readOGR(dsn=landGDB,layer="Land50k_Maritimes",stringsAsFactors=F)
```
```{r Define PEZ!, echo=FALSE, include=FALSE, cache=FALSE}
pl <- list.files(polyPath,"*.shp")
pl <- pl[-grep("xml",pl)]
PEZ_poly <- readOGR(file.path(polyPath,pl[grep(paste0("PEZ_",AquaSiteName,PEZversion),pl)]))
```

```{r echo=FALSE, results='asis'}
cat(AquaSiteName)
```

```{r Fig 1 PEZ polygon, fig.height=8, fig.width=11}
site_map(PEZ_poly,site,land,40)
```

```{r read wsdb and filter SARA & COSEWIC cetacean spp, echo=FALSE, include=FALSE, cache=FALSE}
wsdb <- read.csv(wsdbFile)
wsdb <- wsdb[which(wsdb$YEAR>=minYear),]

wsdb_filter <- filter_wsdb(wsdb)
```
```{r Fig 4 Whale Sightings Database, fig.height=8, fig.width=11}
par(mfrow = c(1,2), mar=c(0, 0, 5.5, 0) + 2)#it goes c(bottom, left, top, right)

site_map(PEZ_poly,site,land,5)
plot_wsdb(PEZ_poly,wsdb_filter,5)
```
