---
title: "Reproducible Report for Species in Maritimes Region - for Internal DFO use only"
author: Synthesis prepared by the Reproducible Reporting Team, steering committee and advisors.
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  html_document:
    theme: paper
    toc: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

```{r setup, echo=FALSE, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, fig.align="left")
library(knitr)
```

# **Appendix**

```{r}
kable(rv_freq_table, caption="RV survey observation records contained within the polygon summarized by species or species group.") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

```{r}
kable(isdb_freq, caption="ISDB observation records contained within the polygon summarized by species or species group.") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

```{r}
kable(marfis_freq, caption="MARFIS observation records contained within the polygon summarized by species or species group.") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```
